### ISSUE TITLE
'ZeroDivisionError: division by zero' while training

### ISSUE THREAD

**Issue by Ankit33-dev** [acoladgroup/OpenNMT-py#21]
Hello everyone,
I am very new to opennmt-py. I am trying to run this model for summarization task.
I am training this model on google colab and using cnndm as a datatset.
The lines that are used for training dataset is 50000 and for validation and testing dataset is 5000.
Number of train_steps is 12000.
When It reached at the 10000 step of training, I got the following error.

[2018-10-10 13:20:14,520 INFO] Step 10000/12000; acc:  99.76; ppl:  1.00; xent: 0.00; lr: 0.15000;  45/ 40 tok/s;  37616 sec
[2018-10-10 13:20:16,528 INFO] Loading valid dataset from data/cnndm/CNNDM.valid.1.pt, number of examples: 0
Traceback (most recent call last):
  File "train.py", line 40, in <module>
    main(opt)
  File "train.py", line 27, in main
    single_main(opt)
  File "/content/gdrive/My Drive/OpenNMT-py/onmt/train_single.py", line 133, in main
    opt.valid_steps)
  File "/content/gdrive/My Drive/OpenNMT-py/onmt/trainer.py", line 196, in train
    step, valid_stats=valid_stats)
  File "/content/gdrive/My Drive/OpenNMT-py/onmt/trainer.py", line 356, in _report_step
    valid_stats=valid_stats)
  File "/content/gdrive/My Drive/OpenNMT-py/onmt/utils/report_manager.py", line 91, in report_step
    lr, step, train_stats=train_stats, valid_stats=valid_stats)
  File "/content/gdrive/My Drive/OpenNMT-py/onmt/utils/report_manager.py", line 147, in _report_step
    self.log('Validation perplexity: %g' % valid_stats.ppl())
  File "/content/gdrive/My Drive/OpenNMT-py/onmt/utils/statistics.py", line 97, in ppl
    return math.exp(min(self.loss / self.n_words, 100))
ZeroDivisionError: division by zero

Can anyone please help me out what I am doing wrong and why I am getting this error? Do I need to increase my dataset for training?
Looking forward for your help.

Thanks in advance

**Comment by ankitcse** [comment]
> post your command lines.

Below is my command line

python train.py -save_model models/cnndm \
                 -data data/cnndm/CNNDM \
                 -copy_attn \
                 -global_attention mlp \
                 -word_vec_size 128 \
                 -rnn_size 512 \
                 -layers 1 \
                 -encoder_type brnn \
                 -train_steps 12000 \
                 -report_every 500\
                 -save_checkpoint_steps 1000\
                 -train_from models/cnndm_step_7000.pt \
                 -max_grad_norm 2 \
                 -dropout 0. \
                 -batch_size 16 \
                 -optim adagrad \
                 -learning_rate 0.15 \
                 -adagrad_accumulator_init 0.1 \
                 -seed 777 \
                 -gpuid 0

**Comment by vince62s** [comment]
not helping
But if you have a division by zero at validation time on n_words = 0
it means your valid set must be empty or wrong.

**Comment by ankitcse** [comment]
> not helping
> But if you have a division by zero at validation time on n_words = 0
> it means your valid set must be empty or wrong.

Thank you for your reply, dataset that I am using is from this link 'https://s3.amazonaws.com/opennmt-models/Summary/cnndm.tar.gz'
After pre-processing step, the valid set I am getting i.e. 'CNNDM.valid.1.pt' is not empty.
But how can I check whether it is right or wrong?

What can i do to fix this error? Do you think increasing number of lines in validation set will help?

**Comment by vince62s** [comment]
My suggestion to start with:
switch to the master repo here https://github.com/OpenNMT/OpenNMT-py
pull to be on master and then try the transformer instead:
https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/Summarization.md
open an issue there if needed.
this repo is more or less to make dev tests.
